services:
  - type: web
    name: prinstine-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production

services:
  - type: web
    name: prinstine-frontend
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l ${PORT:-3000}
    envVars:
      - key: REACT_APP_API_URL
        sync: false

